apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo

resources:
  - namespace.yaml
  - github.com/argoproj/argo-workflows//manifests/cluster-install?ref=v3.2.3
  - ingressroute.yaml

transformers:
  - server-deployment-patch.yaml
