apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db
    spec:
      containers:
        - name: db
          image: grafana/tns-db:9c1ab38
          ports:
            - containerPort: 80
          args:
            - -log.level=debug
          env:
            - name: JAEGER_AGENT_HOST
              value: tempo.tempo.svc.cluster.local
            - name: JAEGER_TAGS
              value: job=tns/db
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
