apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app.kubernetes.io/name: app
    release: kube-prometheus-stack
spec:
  selector:
    app.kubernetes.io/name: db
  ports:
    - name: http
      port: 8000
      targetPort: 80
