apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loadgen
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loadgen
    spec:
      containers:
        - name: loadgen
          image: grafana/tns-loadgen:9c1ab38
          ports:
            - containerPort: 80
          args:
            - -log.level=debug
            - http://app:8001
          env:
            - name: JAEGER_AGENT_HOST
              value: tempo.tempo.svc.cluster.local
            - name: JAEGER_TAGS
              value: job=tns/loadgen
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
