apiVersion: v1
kind: Service
metadata:
  name: loadgen
  labels:
    app.kubernetes.io/name: app
    release: kube-prometheus-stack
spec:
  selector:
    app.kubernetes.io/name: loadgen
  ports:
    - name: http
      port: 8002
      targetPort: 80
