apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tns
  labels:
    release: kube-prometheus-stack
spec:
  jobLabel: tns
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: Exists
  namespaceSelector:
    matchNames:
      - tns
  endpoints:
    - port: http
      interval: 15s
