apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# TODO This causes the deploy to fail. Why?
#namespace: cert-manager

generators:
  - helmchart.yaml

resources:
  - namespace.yaml
  - clusterissuer.yaml
