# https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
# nonk8s
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: kube-prometheus-stack
name: kube-prometheus-stack
repo: https://prometheus-community.github.io/helm-charts
version: 34.10.0
releaseName: kube-prometheus-stack
namespace: prometheus
valuesInLine:
  namespaceOverride: prometheus
  prometheus:
    enabled: true
    ingress:
      enabled: false
      hosts:
        - prometheus.127-0-0-1.nip.io
  alertmanager:
    enabled: true
    ingress:
      enabled: false
      hosts:
        - alertmanager.127-0-0-1.nip.io
  grafana:
    enabled: false
    forceDeployDatasources: true
    forceDeployDashboards: true
    defaultDashboardsEnabled: true
