apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - helmchart.yaml

resources:
  - kapp-config.yaml
  - namespace.yaml
  - grafanasecrets.yaml
  - charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml
  - charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml
  - charts/kube-prometheus-stack/crds/crd-podmonitors.yaml
  - charts/kube-prometheus-stack/crds/crd-probes.yaml
  - charts/kube-prometheus-stack/crds/crd-prometheuses.yaml
  - charts/kube-prometheus-stack/crds/crd-prometheusrules.yaml
  - charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml
  - charts/kube-prometheus-stack/crds/crd-thanosrulers.yaml
  - ingressroutes.yaml
