apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

configMapGenerator:
  # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cmd-params-cm.yaml
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - server.insecure="true"
      - server.disable.auth="true"

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.5/manifests/install.yaml
  - ingressroute.yaml
